[project]
name = "fp-smart-connect"
version = "0.1.1"
description = "Fisher-Price Smart Connect integration for Home Assistant"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = ["fp-soother-lib>=1.0.2"]

[dependency-groups]
dev = [
    "aiousbwatcher==1.1.2",
    "dbus-fast",
    "homeassistant>=2026.9.1",
    "pytest-homeassistant-custom-component==0.13.364",
    "ruff>=0.16.6",
    "serialx==1.10.0",
    "ty>=0.0.82",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
pythonpath = ["."]

[tool.uv]
exclude-newer-package = { fp-soother-lib = false }
