set_playlist:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: fp_smart_connect
    playlist:
      required: true
      selector:
        select:
          options:
            - settling
            - soothing
          translation_key: playlist
    tracks:
      required: true
      example: '["Aurora", "Six Little Ducks"]'
      selector:
        select:
          options:
            - It's Raining, It's Pouring
            - Aurora
            - Six Little Ducks
            - Frere Jacques
            - "Brahms: Lullaby"
            - Somewhere
            - Daylight
            - Dreaming Dawn
            - Motions
            - Polar Wind
          multiple: true
          custom_value: true
apply_preset:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: fp_smart_connect
    play_mode:
      selector:
        boolean: {}
    sound_mode:
      selector:
        select:
          options:
            - "off"
            - pink_noise
            - brown_noise
            - womb
            - ocean
            - nature
            - wind
            - its_raining_its_pouring
            - aurora
            - six_little_ducks
            - frere_jacques
            - brahms_lullaby
            - somewhere
            - daylight
            - dreaming_dawn
            - motions
            - polar_wind
          translation_key: sound_mode
    volume_level:
      selector:
        number:
          min: 0
          max: 15
          mode: slider
    animal_projection_mode:
      selector:
        select:
          options:
            - "off"
            - "on"
            - lighthouse
            - candle
          translation_key: animal_projection_mode
    animal_projection_brightness:
      selector:
        number:
          min: 0
          max: 10
          mode: slider
    animal_projection_speed:
      selector:
        select:
          options:
            - slow
            - fast
          translation_key: animal_projection_speed
    star_projection_sequence_mode:
      selector:
        select:
          options:
            - "off"
            - rainbow
            - cool_colors
            - warm_colors
            - custom
          translation_key: star_projection_mode
    star_projection_custom_color0:
      selector:
        select:
          options:
            - "off"
            - red
            - orange
            - yellow
            - green
            - blue
            - purple
          translation_key: star_color
    star_projection_custom_color1:
      selector:
        select:
          options:
            - "off"
            - red
            - orange
            - yellow
            - green
            - blue
            - purple
          translation_key: star_color
    star_projection_custom_color2:
      selector:
        select:
          options:
            - "off"
            - red
            - orange
            - yellow
            - green
            - blue
            - purple
          translation_key: star_color
    star_projection_brightness:
      selector:
        number:
          min: 0
          max: 6
          mode: slider
    star_projection_speed:
      selector:
        select:
          options:
            - slow
            - normal
            - fast
            - very_fast
          translation_key: star_projection_speed
    nightlight_mode:
      selector:
        boolean: {}
    nightlight_brightness:
      selector:
        number:
          min: 0
          max: 7
          mode: slider
    sleep_stages_mode:
      selector:
        select:
          options:
            - "off"
            - settle
            - soothe
            - sleep
          translation_key: sleep_stages_mode
    captive_playlist_selection:
      selector:
        select:
          options:
            - It's Raining, It's Pouring
            - Aurora
            - Six Little Ducks
            - Frere Jacques
            - "Brahms: Lullaby"
          multiple: true
          custom_value: true
    soothe_playlist_selection:
      selector:
        select:
          options:
            - Somewhere
            - Daylight
            - Dreaming Dawn
            - Motions
            - Polar Wind
          multiple: true
          custom_value: true
    sound_timer_setting:
      selector:
        select:
          options:
            - 5_minutes
            - 10_minutes
            - 15_minutes
            - 20_minutes
            - 25_minutes
            - 30_minutes
            - 60_minutes
            - 90_minutes
            - continuous
          translation_key: timer
    light_timer:
      selector:
        select:
          options:
            - 5_minutes
            - 10_minutes
            - 15_minutes
            - 20_minutes
            - 25_minutes
            - 30_minutes
            - 60_minutes
            - 90_minutes
            - continuous
          translation_key: timer
    previous_animal_projection_mode:
      selector:
        select:
          options:
            - "off"
            - "on"
            - lighthouse
            - candle
          translation_key: animal_projection_mode
    previous_star_projection_sequence_mode:
      selector:
        select:
          options:
            - "off"
            - rainbow
            - cool_colors
            - warm_colors
            - custom
          translation_key: star_projection_mode
